name: Lint Code with Pylint (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: windows-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
           python -m pip install pylint

      # Run Pylint
      - name: Run Pylint
        shell: pwsh
        run: |
          python -m pylint unit-converter.py



